"""
プラグインレジストリのビルダー。

`plugins/` を走査して各 `<name>/plugin.py` を import、PLUGIN 定数を集めて
`plugins/_generated_registry.py` に静的 import を出力する。

使い方:
    uv run python -m src.plugins_build

出力ファイルは .gitignore で除外想定。CI/本番で起動前に毎回再生成するか、
プラグイン追加時に手動実行する運用。
"""
from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

import tomllib

from src.plugin_api import ServiceSpec
from src.plugins_loader import PLUGINS_DIR, discover_dynamic

OUTPUT = PLUGINS_DIR / "_generated_registry.py"
_PLUGINS_CONFIG = Path(__file__).parent.parent / "config" / "plugins.toml"


def _enabled_set() -> set[str] | None:
    """config/plugins.toml の enabled リストを返す。ファイル無ければ None (= 全許可)。"""
    if not _PLUGINS_CONFIG.exists():
        return None
    with _PLUGINS_CONFIG.open("rb") as f:
        cfg = tomllib.load(f)
    enabled = cfg.get("enabled")
    return set(enabled) if enabled else None


def build() -> tuple[int, int]:
    """検出結果を _generated_registry.py に書き出し、(成功数, 失敗数) を返す。"""
    PLUGINS_DIR.mkdir(parents=True, exist_ok=True)
    init_py = PLUGINS_DIR / "__init__.py"
    if not init_py.exists():
        init_py.write_text("")

    discovered: dict[str, ServiceSpec] = discover_dynamic()
    allowed = _enabled_set()
    if allowed is not None:
        discovered = {k: v for k, v in discovered.items() if k in allowed}
    if not discovered:
        OUTPUT.write_text(_render_empty())
        print("[build] プラグイン未検出")
        return (0, 0)

    lines: list[str] = [
        '"""DO NOT EDIT — generated by `python -m src.plugins_build`."""',
        f"# generated_at: {datetime.now().isoformat(timespec='seconds')}",
        "from __future__ import annotations",
        "",
    ]
    for name in sorted(discovered.keys()):
        lines.append(f"from plugins.{name}.plugin import PLUGIN as _{_safe_id(name)}")
    lines.append("")
    lines.append("REGISTRY = {")
    for name in sorted(discovered.keys()):
        lines.append(f"    _{_safe_id(name)}.name: _{_safe_id(name)},")
    lines.append("}")
    lines.append("")

    OUTPUT.write_text("\n".join(lines))
    print(f"[build] {len(discovered)} プラグインを {OUTPUT.relative_to(PLUGINS_DIR.parent)} に書込:")
    for name in sorted(discovered.keys()):
        spec = discovered[name]
        print(f"  - {spec.name:20} {spec.display_name}")
    return (len(discovered), 0)


def _safe_id(name: str) -> str:
    return name.replace("-", "_").replace(".", "_")


def _render_empty() -> str:
    return (
        '"""DO NOT EDIT — generated by `python -m src.plugins_build`."""\n'
        f"# generated_at: {datetime.now().isoformat(timespec='seconds')}\n"
        "REGISTRY = {}\n"
    )


if __name__ == "__main__":
    ok, fail = build()
    sys.exit(0 if fail == 0 else 1)
